"""
工具模块 - Prompt模板、辅助函数等
"""

from .prompts import (
    DISPATCHER_SYSTEM_PROMPT,
    CRAFT_EXPERT_SYSTEM_PROMPT,
    HISTORY_EXPERT_SYSTEM_PROMPT,
    HERITAGE_EXPERT_SYSTEM_PROMPT,
    GAP_DETECTION_PROMPT,
    NARRATIVE_GENERATION_PROMPT,
    GRANULARITY_PROMPTS,
    get_adaptive_prompt,
)

__all__ = [
    "DISPATCHER_SYSTEM_PROMPT",
    "CRAFT_EXPERT_SYSTEM_PROMPT",
    "HISTORY_EXPERT_SYSTEM_PROMPT",
    "HERITAGE_EXPERT_SYSTEM_PROMPT",
    "GAP_DETECTION_PROMPT",
    "NARRATIVE_GENERATION_PROMPT",
    "GRANULARITY_PROMPTS",
    "get_adaptive_prompt",
]
