<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getAdminAgents, getAdminEvaluations, getAdminFeedback, updateAdminAgent } from '@/api/admin'
import type { AdminAgentConfiguration, AdminEvaluationRecord, AdminFeedbackRecord } from '@/types'
type Tab = 'evaluations' | 'feedback' | 'agents'
const tab = ref<Tab>('evaluations'); const agents = ref<AdminAgentConfiguration[]>([]); const evaluations = ref<AdminEvaluationRecord[]>([]); const feedback = ref<AdminFeedbackRecord[]>([]); const loading = ref(true); const scoreFloor = ref(0); const sentiment = ref<'all' | 'up' | 'down'>('all')
const visibleEvaluations = computed(() => evaluations.value.filter(item => item.score >= scoreFloor.value))
const visibleFeedback = computed(() => feedback.value.filter(item => sentiment.value === 'all' || item.sentiment === sentiment.value))
async function load() { loading.value = true; try { const [a, e, f] = await Promise.all([getAdminAgents(), getAdminEvaluations(), getAdminFeedback()]); agents.value = a.items; evaluations.value = e.items; feedback.value = f.items } catch { ElMessage.error('无法读取管理数据，请检查管理员权限') } finally { loading.value = false } }
async function save(agent: AdminAgentConfiguration) { try { await updateAdminAgent(agent.agent_id, { enabled: agent.enabled, display_name: agent.display_name, capability: agent.capability, collaboration_priority: agent.collaboration_priority, parameters: agent.parameters }); ElMessage.success('已保存；仅影响后续新请求') } catch { ElMessage.error('保存失败，请检查参数') } }
onMounted(load)
</script>
<template>
  <section class="max-w-5xl mx-auto px-6 py-10"><p class="text-[12px] tracking-wider text-[var(--accent)] mb-2">ADMINISTRATION</p><h1 class="text-2xl font-semibold mb-2">质量与 Agent 管理后台</h1><p class="text-[14px] text-[var(--text-secondary)] mb-6">评分是可解释的过程质量信号，不代表事实正确率。</p>
    <div class="tabs mb-5"><button v-for="item in ([['evaluations','质量评估'], ['feedback','用户反馈'], ['agents','专家配置']] as [Tab, string][])" :key="item[0]" :class="{ active: tab === item[0] }" @click="tab = item[0]">{{ item[1] }}</button></div><div v-if="loading" class="caption">加载管理数据中…</div>
    <template v-else-if="tab === 'evaluations'"><label class="text-sm">最低分数 <input v-model.number="scoreFloor" type="number" min="0" max="100" class="small-field" /></label><p class="caption mt-3">共 {{ visibleEvaluations.length }} 条。</p><article v-for="item in visibleEvaluations" :key="item.chat_id" class="card mt-3"><div class="flex justify-between gap-3"><strong>{{ item.score }}/100 · {{ item.rule_version }}</strong><span class="caption">{{ new Date(item.created_at).toLocaleString() }}</span></div><p class="mt-2 text-sm">问：{{ item.question }}</p><p class="caption answer">答：{{ item.answer }}</p><details class="mt-2"><summary>评分明细</summary><ul><li v-for="detail in item.details" :key="detail.code">{{ detail.reason }}：{{ detail.score }}/{{ detail.max_score }}</li></ul></details></article></template>
    <template v-else-if="tab === 'feedback'"><label class="text-sm">反馈类型 <select v-model="sentiment" class="small-field"><option value="all">全部</option><option value="up">有帮助</option><option value="down">无帮助</option></select></label><p class="caption mt-3">共 {{ visibleFeedback.length }} 条。</p><article v-for="item in visibleFeedback" :key="item.id" class="card mt-3"><strong>{{ item.sentiment === 'up' ? '👍 有帮助' : '👎 无帮助' }}</strong><span class="caption ml-2">{{ new Date(item.updated_at).toLocaleString() }}</span><p class="mt-2 text-sm">问：{{ item.question }}</p><p v-if="item.comment" class="caption">意见：{{ item.comment }}</p></article></template>
    <template v-else><p class="caption mb-3">配置仅影响后续新请求；全部禁用会自动安全回退默认专家。</p><article v-for="agent in agents" :key="agent.agent_id" class="card mt-3"><div class="flex justify-between gap-3 mb-3"><strong>{{ agent.agent_id }}</strong><label><input v-model="agent.enabled" type="checkbox" /> 启用</label></div><div class="grid md:grid-cols-2 gap-3 text-sm"><label>展示名称<input v-model="agent.display_name" class="field" /></label><label>协作优先级<input v-model.number="agent.collaboration_priority" type="number" min="1" max="1000" class="field" /></label><label class="md:col-span-2">能力说明<input v-model="agent.capability" class="field" /></label></div><button class="save" @click="save(agent)">保存配置</button></article></template>
  </section>
</template>
<style scoped>.tabs{display:flex;gap:8px;border-bottom:1px solid var(--border)}.tabs button{border:0;background:transparent;padding:8px 12px;color:var(--text-tertiary);cursor:pointer}.tabs button.active{color:var(--accent);border-bottom:2px solid var(--accent)}.card{border:1px solid var(--border);border-radius:12px;padding:16px;background:var(--surface)}.field{display:block;width:100%;margin-top:5px;border:1px solid var(--border);border-radius:8px;padding:7px 9px;background:var(--bg)}.small-field{margin-left:6px;border:1px solid var(--border);border-radius:6px;padding:4px 6px;background:var(--surface)}.answer{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.save{margin-top:16px;padding:8px 16px;border:0;border-radius:8px;background:var(--text);color:white;cursor:pointer}</style>
