<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import {
  approveGraphCandidate, createAdminCraft, createAdminInheritor, deleteAdminCraft, deleteAdminInheritor,
  getAdminAgents, getAdminCrafts, getAdminEvaluations, getAdminFeedback, getAdminInheritors, getAuditLogs,
  getGraphCandidates, publishAdminCraft, publishAdminInheritor, rejectGraphCandidate, scanGraphCandidates,
  updateAdminAgent, updateAdminCraft, updateAdminInheritor,
  type AdminCraft, type AdminInheritor, type AuditLog, type GraphCandidate,
} from '@/api/admin'
import type { AdminAgentConfiguration, AdminEvaluationRecord, AdminFeedbackRecord } from '@/types'

type Tab = 'evaluations' | 'feedback' | 'agents' | 'crafts' | 'inheritors' | 'graph' | 'audit'
const tab = ref<Tab>('evaluations')
const agents = ref<AdminAgentConfiguration[]>([]); const evaluations = ref<AdminEvaluationRecord[]>([]); const feedback = ref<AdminFeedbackRecord[]>([])
const crafts = ref<AdminCraft[]>([]); const inheritors = ref<AdminInheritor[]>([]); const candidates = ref<GraphCandidate[]>([]); const audits = ref<AuditLog[]>([])
const loading = ref(true); const scoreFloor = ref(0); const sentiment = ref<'all' | 'up' | 'down'>('all')
const craftDraft = ref({ name: '', summary: '', content: '' })
const inheritorDraft = ref({ name: '', craft_name: '', region: '', biography: '', source_url: '', source_name: '', evidence_text: '' })
const visibleEvaluations = computed(() => evaluations.value.filter(item => item.score >= scoreFloor.value))
const visibleFeedback = computed(() => feedback.value.filter(item => sentiment.value === 'all' || item.sentiment === sentiment.value))

async function load() {
  loading.value = true
  try {
    const [a, e, f, c, i, g, l] = await Promise.all([getAdminAgents(), getAdminEvaluations(), getAdminFeedback(), getAdminCrafts(), getAdminInheritors(), getGraphCandidates(), getAuditLogs()])
    agents.value = a.items; evaluations.value = e.items; feedback.value = f.items; crafts.value = c.items; inheritors.value = i.items; candidates.value = g.items; audits.value = l.items
  } catch { ElMessage.error('无法读取管理数据，请检查管理员权限') } finally { loading.value = false }
}
async function save(agent: AdminAgentConfiguration) { try { await updateAdminAgent(agent.agent_id, { enabled: agent.enabled, display_name: agent.display_name, capability: agent.capability, collaboration_priority: agent.collaboration_priority, parameters: agent.parameters }); ElMessage.success('已保存；仅影响后续新请求') } catch { ElMessage.error('保存失败，请检查参数') } }
async function addCraft() { try { await createAdminCraft(craftDraft.value); craftDraft.value = { name: '', summary: '', content: '' }; await load(); ElMessage.success('百科草稿已创建') } catch { ElMessage.error('创建失败：名称不能重复') } }
async function saveCraft(item: AdminCraft) { try { await updateAdminCraft(item.id, item); ElMessage.success('百科草稿已保存') } catch { ElMessage.error('保存失败') } }
async function publishCraft(id: number) { try { await publishAdminCraft(id); await load(); ElMessage.success('已发布并生成待审核图谱候选') } catch { ElMessage.error('发布失败') } }
async function removeCraft(id: number) { if (!window.confirm('确认删除该百科草稿/条目？')) return; try { await deleteAdminCraft(id); await load(); ElMessage.success('已删除') } catch { ElMessage.error('删除失败') } }
async function addInheritor() { try { await createAdminInheritor(inheritorDraft.value); inheritorDraft.value = { name: '', craft_name: '', region: '', biography: '', source_url: '', source_name: '', evidence_text: '' }; await load(); ElMessage.success('传承人草稿已创建') } catch { ElMessage.error('创建失败，请检查公开来源') } }
async function saveInheritor(item: AdminInheritor) { try { await updateAdminInheritor(item.id, item); ElMessage.success('档案已保存') } catch { ElMessage.error('保存失败') } }
async function publishInheritor(id: number) { try { await publishAdminInheritor(id); await load(); ElMessage.success('档案已发布') } catch { ElMessage.error('发布失败：必须保留公开来源证据') } }
async function removeInheritor(id: number) { if (!window.confirm('确认删除该传承人档案？')) return; try { await deleteAdminInheritor(id); await load(); ElMessage.success('已删除') } catch { ElMessage.error('删除失败') } }
async function scanGraph() { try { const result = await scanGraphCandidates(); await load(); ElMessage.success(`扫描 ${result.scanned} 条已发布百科，新增 ${result.created} 个候选`) } catch { ElMessage.error('扫描失败') } }
async function approve(id: number) { try { await approveGraphCandidate(id); await load(); ElMessage.success('已审核并合并到图谱') } catch { ElMessage.error('审核合并失败') } }
async function reject(id: number) { try { await rejectGraphCandidate(id, window.prompt('可选：填写拒绝原因') || ''); await load(); ElMessage.success('已拒绝') } catch { ElMessage.error('操作失败') } }
onMounted(load)
</script>
<template>
  <section class="max-w-5xl mx-auto px-6 py-10"><p class="text-[12px] tracking-wider text-[var(--accent)] mb-2">ADMINISTRATION</p><h1 class="text-2xl font-semibold mb-2">平台管理后台</h1><p class="text-[14px] text-[var(--text-secondary)] mb-6">百科、传承人和图谱变更均保留操作审计；图谱扫描仅由管理员手动触发。</p>
    <div class="tabs mb-5"><button v-for="item in ([['evaluations','质量评估'], ['feedback','用户反馈'], ['agents','专家配置'], ['crafts','百科条目'], ['inheritors','传承人'], ['graph','图谱候选'], ['audit','审计日志']] as [Tab, string][])" :key="item[0]" :class="{ active: tab === item[0] }" @click="tab = item[0]">{{ item[1] }}</button></div><div v-if="loading" class="caption">加载管理数据中…</div>
    <template v-else-if="tab === 'evaluations'"><label class="text-sm">最低分数 <input v-model.number="scoreFloor" type="number" min="0" max="100" class="small-field" /></label><p class="caption mt-3">共 {{ visibleEvaluations.length }} 条。</p><article v-for="item in visibleEvaluations" :key="item.chat_id" class="card mt-3"><div class="flex justify-between gap-3"><strong>{{ item.score }}/100 · {{ item.rule_version }}</strong><span class="caption">{{ new Date(item.created_at).toLocaleString() }}</span></div><p class="mt-2 text-sm">问：{{ item.question }}</p><p class="caption answer">答：{{ item.answer }}</p><details class="mt-2"><summary>评分明细</summary><ul><li v-for="detail in item.details" :key="detail.code">{{ detail.reason }}：{{ detail.score }}/{{ detail.max_score }}</li></ul></details></article></template>
    <template v-else-if="tab === 'feedback'"><label class="text-sm">反馈类型 <select v-model="sentiment" class="small-field"><option value="all">全部</option><option value="up">有帮助</option><option value="down">无帮助</option></select></label><p class="caption mt-3">共 {{ visibleFeedback.length }} 条。</p><article v-for="item in visibleFeedback" :key="item.id" class="card mt-3"><strong>{{ item.sentiment === 'up' ? '👍 有帮助' : '👎 无帮助' }}</strong><span class="caption ml-2">{{ new Date(item.updated_at).toLocaleString() }}</span><p class="mt-2 text-sm">问：{{ item.question }}</p><p v-if="item.comment" class="caption">意见：{{ item.comment }}</p></article></template>
    <template v-else-if="tab === 'agents'"><p class="caption mb-3">配置仅影响后续新请求；全部禁用会自动安全回退默认专家。</p><article v-for="agent in agents" :key="agent.agent_id" class="card mt-3"><div class="flex justify-between gap-3 mb-3"><strong>{{ agent.agent_id }}</strong><label><input v-model="agent.enabled" type="checkbox" /> 启用</label></div><div class="grid md:grid-cols-2 gap-3 text-sm"><label>展示名称<input v-model="agent.display_name" class="field" /></label><label>协作优先级<input v-model.number="agent.collaboration_priority" type="number" min="1" max="1000" class="field" /></label><label class="md:col-span-2">能力说明<input v-model="agent.capability" class="field" /></label></div><button class="save" @click="save(agent)">保存配置</button></article></template>
    <template v-else-if="tab === 'crafts'"><article class="card"><h2>新建百科草稿</h2><div class="grid gap-3 mt-3"><input v-model="craftDraft.name" class="field" placeholder="技艺名称" /><input v-model="craftDraft.summary" class="field" placeholder="摘要" /><textarea v-model="craftDraft.content" class="field" rows="4" placeholder="正文（发布后会生成图谱审核候选）" /></div><button class="save" @click="addCraft">创建草稿</button></article><article v-for="item in crafts" :key="item.id" class="card mt-3"><div class="flex justify-between"><strong>{{ item.name }} · {{ item.status }}</strong><div class="actions"><button @click="saveCraft(item)">保存</button><button v-if="item.status !== 'published'" @click="publishCraft(item.id)">发布</button><button class="danger" @click="removeCraft(item.id)">删除</button></div></div><input v-model="item.name" class="field" /><input v-model="item.summary" class="field" /><textarea v-model="item.content" class="field" rows="4" /></article></template>
    <template v-else-if="tab === 'inheritors'"><article class="card"><h2>新建传承人草稿</h2><div class="grid md:grid-cols-2 gap-3 mt-3"><input v-model="inheritorDraft.name" class="field" placeholder="姓名" /><input v-model="inheritorDraft.craft_name" class="field" placeholder="对应技艺" /><input v-model="inheritorDraft.region" class="field" placeholder="地区" /><input v-model="inheritorDraft.source_name" class="field" placeholder="来源名称" /><input v-model="inheritorDraft.source_url" class="field md:col-span-2" placeholder="公开来源 URL（必填）" /><textarea v-model="inheritorDraft.biography" class="field" rows="3" placeholder="生平简介" /><textarea v-model="inheritorDraft.evidence_text" class="field" rows="3" placeholder="来源证据摘要（必填）" /></div><button class="save" @click="addInheritor">创建草稿</button></article><article v-for="item in inheritors" :key="item.id" class="card mt-3"><div class="flex justify-between"><strong>{{ item.name }} · {{ item.status }}</strong><div class="actions"><button @click="saveInheritor(item)">保存</button><button v-if="item.status !== 'published'" @click="publishInheritor(item.id)">发布</button><button class="danger" @click="removeInheritor(item.id)">删除</button></div></div><input v-model="item.craft_name" class="field" /><input v-model="item.region" class="field" /><textarea v-model="item.biography" class="field" rows="3" /></article></template>
    <template v-else-if="tab === 'graph'"><div class="flex justify-between items-center"><p class="caption">扫描不会自动运行，也不会在服务器安装 cron。</p><button class="save" @click="scanGraph">立即扫描已发布百科</button></div><article v-for="item in candidates" :key="item.id" class="card mt-3"><div class="flex justify-between"><strong>{{ item.source_entity }} — {{ item.relation }} → {{ item.target_entity }}</strong><span>{{ item.status }}</span></div><p class="caption mt-2">{{ item.evidence_text }}</p><a :href="item.source_url" target="_blank" rel="noreferrer" class="caption">证据来源</a><div v-if="item.status === 'pending'" class="actions mt-3"><button @click="approve(item.id)">审核合并</button><button class="danger" @click="reject(item.id)">拒绝</button></div></article></template>
    <template v-else><article v-for="item in audits" :key="item.id" class="card mt-3"><strong>{{ item.action }}</strong><span class="caption ml-2">{{ item.subject_type }} #{{ item.subject_id }} · {{ new Date(item.created_at).toLocaleString() }}</span><p v-if="item.detail" class="caption mt-2">{{ item.detail }}</p></article></template>
  </section>
</template>
<style scoped>.tabs{display:flex;gap:8px;border-bottom:1px solid var(--border);overflow-x:auto}.tabs button,.actions button{border:0;background:transparent;padding:8px 12px;color:var(--text-tertiary);cursor:pointer}.tabs button.active{color:var(--accent);border-bottom:2px solid var(--accent)}.card{border:1px solid var(--border);border-radius:12px;padding:16px;background:var(--surface)}.field{display:block;width:100%;margin-top:8px;border:1px solid var(--border);border-radius:8px;padding:7px 9px;background:var(--bg)}.small-field{margin-left:6px;border:1px solid var(--border);border-radius:6px;padding:4px 6px;background:var(--surface)}.answer{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.save{margin-top:16px;padding:8px 16px;border:0;border-radius:8px;background:var(--text);color:white;cursor:pointer}.actions{display:flex;gap:4px}.actions button{border:1px solid var(--border);border-radius:6px}.actions .danger{color:#b42318}</style>
