<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { listEncyclopedia, type CraftEntry } from '@/api/platform'
const entries = ref<CraftEntry[]>([])
const error = ref('')
onMounted(async () => { try { entries.value = await listEncyclopedia() } catch { error.value = '百科暂时不可用，请稍后重试。' } })
</script>
<template><main class="encyclopedia"><header><p>技艺百科</p><h1>循着工艺，读见传承</h1><span>已发布的非遗知识条目，以现有服务端内容为准。</span></header><p v-if="error" class="state error">{{ error }}</p><p v-else-if="!entries.length" class="state">暂未发布百科条目。</p><div v-else class="entries"><router-link v-for="entry in entries" :key="entry.slug" :to="`/encyclopedia/${entry.slug}`"><img :src="`/crafts/${entry.name}.jpg`" :alt="entry.name"/><div><h2>{{ entry.name }}</h2><p>{{ entry.summary }}</p><span>阅读条目 →</span></div></router-link></div></main></template>
<style scoped>.encyclopedia{max-width:1120px;margin:auto;padding:58px 24px 86px}.encyclopedia header{margin-bottom:32px}.encyclopedia header>p{margin:0 0 7px;color:var(--accent);font-size:.7rem;font-weight:700;letter-spacing:.2em}.encyclopedia h1{margin:0;font-family:var(--font-brush);font-size:3.4rem;font-weight:400;letter-spacing:.12em}.encyclopedia header>span{display:block;margin-top:12px;color:var(--text-secondary);font-size:.85rem}.entries{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.entries a{overflow:hidden;background:#fffaf0;border:1px solid rgba(82,61,36,.16);color:var(--text);text-decoration:none}.entries img{width:100%;height:185px;object-fit:cover;filter:saturate(.76)}.entries div{padding:18px}.entries h2{margin:0;font-family:var(--font-brush);font-size:2rem;font-weight:400;letter-spacing:.1em}.entries p{display:-webkit-box;overflow:hidden;min-height:43px;margin:8px 0 14px;color:var(--text-secondary);font-size:.78rem;line-height:1.7;-webkit-box-orient:vertical;-webkit-line-clamp:2}.entries span{color:var(--accent);font-size:.72rem}.state{color:var(--text-tertiary)}.error{color:#b33d30}@media(max-width:760px){.entries{grid-template-columns:repeat(2,1fr)}.encyclopedia h1{font-size:2.7rem}}@media(max-width:480px){.encyclopedia{padding:36px 18px 60px}.entries{grid-template-columns:1fr}}</style>
